### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by DomGarguilo** [milkmull/Card-Game#2]
https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/
https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by DomGarguilo** [comment]
also add `ips.txt` to the .gitignore so that changes to that file are not pushed to github

**Comment by milkmull** [comment]
closed via 0efa9152994f1445a2d9b9dacb0579700f866bc1
